version: '26.x.{build}'

image:
  - Visual Studio 2019

environment:
  matrix:
    - compiler: MSVC

shallow_clone: true

test: off

deploy: off

matrix:
  fast_finish: true

# No reversion when shallow clone is enabled.
before_build:
  - cmd: |
      ECHO Update Version Hash
      "c:/Program Files/Git/usr/bin/sed" -i "s/\(.\+\)[0-9a-f]\{8\}\(.\+\)/\1%APPVEYOR_REPO_COMMIT:~0,8%\2/gm" ./src/VersionRev.h ./matepath/src/VersionRev.h

build_script:
  - cmd: |
      CALL "build\VisualStudio\build.bat" Build x64 Release 1
      CALL "locale\build.bat" Build x64 Release 1
      CALL "build\make_zip.bat" MSVC x64 Release Locale 1

artifacts:
  - path: 'build\Notepad_i18n_x64_*.zip'
    name: Notepad_x64
